import { describe, expect, it } from "vitest";

import { none } from "../option.js";

import type { DiagnosticCode } from "./code.js";
import { errorDiagnostic, warningDiagnostic } from "./diagnostic.js";
import { CODE_BY_KIND, codeOf, type DiagnosticKind } from "./kind.js";
import { renderDiagnosticMessage } from "./message.js";

/**
 * One instance per `DiagnosticKind` variant. `tsc`'s `assertNever` in
 * `codeOf`/`renderDiagnosticMessage` already forces a new variant to be
 * handled; this list forces it to also be exercised, so a payload-shape
 * mistake (a `${kind.naem}` typo, a missing field) fails a test rather than
 * shipping `undefined` into a diagnostic.
 */
const SAMPLE_KINDS: readonly DiagnosticKind[] = [
  { kind: "LexUnterminatedStringLiteral", offset: 3 },
  { kind: "LexUnterminatedRawStringLiteral", offset: 3 },
  { kind: "LexUnterminatedCharLiteral", offset: 3 },
  { kind: "LexUnterminatedBlockComment" },
  { kind: "LexEmptyCharLiteral", offset: 3 },
  { kind: "LexUnexpectedCharacter", character: "$", offset: 3 },
  { kind: "LexRawIdentifierPrefixIncomplete" },
  { kind: "LexRawStringPrefixIncomplete", prefix: "r#" },
  { kind: "LexReadPastEnd", index: 5, sourceLength: 4 },
  { kind: "LexFloatExponentNoDigits", offset: 3 },
  { kind: "LexUnterminatedFloatLiteral", offset: 3 },
  { kind: "LexRadixLiteralNoDigits", radix: "hex", offset: 3 },
  { kind: "LexRadixLiteralLeadingUnderscore", radix: "octal", offset: 3 },
  { kind: "LexInvalidRadixDigit", radix: "binary", character: "2", offset: 3 },
  { kind: "LexHexEscapeNeedsTwoDigits", offset: 3 },
  { kind: "LexUnicodeEscapeNoOpeningBrace", offset: 3 },
  { kind: "LexUnicodeEscapeNoDigits", offset: 3 },
  { kind: "LexUnicodeEscapeNoClosingBrace", offset: 3 },
  { kind: "LexUnicodeEscapeTooManyDigits", offset: 3 },
  { kind: "LexUnicodeEscapeOutOfRange", codepoint: "FFFFFF", offset: 3 },
  { kind: "LexUnicodeEscapeSurrogate", codepoint: "D800", offset: 3 },
  { kind: "LexUnknownEscapeSequence", sequence: "q", offset: 3 },
  { kind: "ParseExpectedFound", expected: "a type", found: "ident", offset: 1 },
  { kind: "ParseExpectedKeyword", keyword: "fn", found: "ident", offset: 1 },
  { kind: "ParseExpectedIdentifierFound", found: "eof", offset: 1 },
  { kind: "ParseExpectedIdentifierAfterPathSep", found: "eof" },
  { kind: "ParseExpectedBraceToStartBlockFound", found: "ident" },
  { kind: "ParseExpectedColonAfterParamName", name: "x" },
  { kind: "ParseExpectedColonAfterFieldName", name: "x" },
  { kind: "ParseExpectedParenAfterMethodGenerics", found: "eof" },
  { kind: "ParseExpectedCommaOrCloseAngleInGenericParams", found: "eof" },
  { kind: "ParseExpectedStructBody", found: "eof" },
  { kind: "ParseExpectedTraitBodyItem", found: "eof" },
  { kind: "ParseExpectedSemiOrCloseBracketInArrayType", found: "eof" },
  { kind: "ParseExpectedCommaOrCloseAngleInTypeArgs", found: "eof" },
  { kind: "ParseExpectedNumericLiteralAfterMinusInPattern", found: "eof" },
  { kind: "ParseExpectedLiteralAfterRangeInPattern", found: "eof" },
  { kind: "ParseExpectedCommaOrParenInParens" },
  { kind: "ParseExpectedSeparatorInArrayLiteral" },
  { kind: "ParseExpectedIfOrBraceAfterElse" },
  { kind: "ParseExpectedBraceToStartIfBody" },
  { kind: "ParseExpectedBraceToStartWhileBody" },
  { kind: "ParseExpectedArrowInMatchArm" },
  { kind: "ParseExpectedCommaBetweenMatchArms" },
  { kind: "ParseExpectedBraceAfterStructUpdate" },
  { kind: "ParseExpectedBraceToCloseStructExpr" },
  { kind: "ParseExpectedParenToCloseArgumentList" },
  { kind: "ParseExpectedExpressionInBrackets" },
  { kind: "ParseExpectedExpressionAfterInclusiveRange" },
  { kind: "ParseExpectedBraceToCloseBlock" },
  { kind: "ParseExpectedCommaOrParenAfterReceiver" },
  { kind: "ParseUnexpectedEndOfInputAtToken", token: 2 },
  { kind: "ParseExpectedCloseBraceEofInBlock" },
  { kind: "ParseExpectedBraceEofToOpenLoopBody" },
  { kind: "ParseExpectedCloseBraceEofInMatch" },
  { kind: "ParseUnterminatedAttributeArgumentList" },
  { kind: "ParseExpectedCloseParenEofInType" },
  { kind: "ParseGuardrailThen", guardrail: "x", rest: "y" },
  { kind: "ParseCannotChainOperators", left: "<", right: ">" },
  { kind: "ParseConstructNotSupported", construct: "lifetime annotations" },
  { kind: "ParseLoopNotSupported", keyword: "while" },
  { kind: "ParseKeywordNotSupported", keyword: "use" },
  { kind: "ParseDeclarationKeywordNotSupported", keyword: "export" },
  { kind: "ParseAsyncNotSupported" },
  { kind: "ParseMutReservedIdentifier" },
  { kind: "ParseNeverTypeNotSupported" },
  { kind: "ParseTupleTypeNotSupported" },
  { kind: "ParseSliceTypeNotSupported" },
  { kind: "ParseDynMustNameTrait" },
  { kind: "ParsePubScopeNotSupported", scope: "crate" },
  { kind: "ParseExpectedType", found: "colon" },
  { kind: "ElisionNoApplicableRule" },
  { kind: "ElisionAmbiguousReturnLifetime", referenceParamCount: 2 },
  { kind: "ParseStrayAngleBracket", context: "trait bound" },
  { kind: "ParseUnexpectedItemKindInBlock", itemKind: "Impl" },
  { kind: "ParseUnexpectedItemKindInImplBody", itemKind: "Let" },
  { kind: "ParseVisibilityNotAllowed", location: "here" },
  { kind: "ParseSigilOnPathPattern" },
  { kind: "ParseSigilOnWildcardPattern", byRef: true },
  { kind: "ParseMutOnFieldlessPattern" },
  { kind: "ParseImmutableBindingNeverUsed" },
  { kind: "ParseStructUpdateUnsupportedInSemantics" },
  { kind: "SemCannotFindName", name: "x" },
  { kind: "SemCannotFindType", name: "T" },
  { kind: "SemCannotFindTrait", name: "T" },
  { kind: "SemNameIsNotATrait", name: "T" },
  { kind: "SemCannotFindEnum", name: "E" },
  { kind: "SemCannotFindStruct", name: "S" },
  { kind: "SemDefinedMoreThanOnce", itemKind: "struct", name: "S" },
  { kind: "SemConstCollidesWithFunction", name: "x" },
  { kind: "SemStaticCollidesWithConst", name: "x" },
  { kind: "SemStaticCollidesWithFunction", name: "x" },
  { kind: "SemFunctionTupleStructNamespaceClash", name: "P" },
  { kind: "SemNoFieldOnStruct", field: "x", structName: "S" },
  { kind: "SemNoFieldOnLabeled", field: "x", label: "variant `V`" },
  { kind: "SemUnknownFieldForStruct", field: "x", structName: "S" },
  { kind: "SemNoVariantOnEnum", variant: "V", enumName: "E" },
  { kind: "SemFieldSpecifiedMoreThanOnce", field: "x" },
  { kind: "SemSelfOutsideTraitOrImpl" },
  { kind: "SemSelfWithoutReceiver" },
  { kind: "SemGenericParamShadowsType", name: "T" },
  { kind: "SemBlanketImplGlobalScope", trait: "Clone" },
  { kind: "SemImplGlobalScope", trait: "Clone", target: "S" },
  { kind: "SemDeclarationShadowsOuter", declKind: "struct", name: "S" },
  { kind: "SemTypeParamNeverUsed", name: "T" },
  { kind: "SemRefutableLetOrParamPattern" },
  { kind: "SemConstInitializerNotConstExpr", name: "X" },
  { kind: "SemConstDefinedInTermsOfItself", name: "X" },
  { kind: "SemConstDivideByZero" },
  { kind: "SemConstShiftOutOfRange" },
  { kind: "SemArrayLengthNotConstExpr" },
  { kind: "SemArrayLengthNotInteger" },
  { kind: "SemArrayLengthNegative" },
  { kind: "SemArrayLengthExceedsMax", value: "5", max: "4" },
  { kind: "SemConflictingImpls", trait: "Clone" },
  { kind: "SemConflictingImplsForType", trait: "Clone", typeName: "S" },
  { kind: "SemTraitAlreadyImplementedForType", trait: "Clone", typeName: "S" },
  { kind: "SemTraitBoundNotSatisfied", typeName: "S", trait: "Clone" },
  { kind: "SemImplMissingMethod", trait: "T", target: "S", method: "m" },
  {
    kind: "SemImplMissingAssociatedType",
    trait: "T",
    target: "S",
    assocName: "A",
  },
  {
    kind: "SemImplDefinesUndeclaredAssocType",
    trait: "T",
    target: "S",
    assocName: "A",
  },
  { kind: "SemAssocTypeNotFoundOnTrait", assocName: "A", trait: "T" },
  { kind: "SemAssocTypeNotFoundAmongBounds", assocName: "A", baseName: "X" },
  { kind: "SemAssocTypeNotFoundOnType", assocName: "A", typeName: "S" },
  { kind: "SemAssocTypeAmbiguous", assocName: "A", traitList: "`T1`, `T2`" },
  { kind: "SemTraitNotObjectSafe", trait: "T", offender: "method `m`" },
  { kind: "SemQualifiedTypePathsUnsupported" },
  { kind: "SemGenericTypeParamNoArguments", name: "T" },
  { kind: "SemPatternKindNotYetSupported" },
  { kind: "SemWhileNotYetSupported" },
  { kind: "SemSignatureNoBodyTopLevel" },
  { kind: "SemSignatureNoBodyInBlock" },
  { kind: "SemTopLevelItemRestriction" },
  { kind: "SemStaticCannotBePub" },
  { kind: "SemConstInitializerTypeMismatch", name: "X", declaredType: "i32" },
  { kind: "SemPatternTypeMismatch", expected: "i32", found: "str" },
  { kind: "SemStaticTypeMismatch" },
  { kind: "SemMissingReturnValue", expected: "i32" },
  { kind: "SemReturnTypeMismatch", expected: "i32", found: "str" },
  { kind: "SemLetAnnotationMismatch" },
  { kind: "SemArrayIndexMustBeUsize", found: "i32" },
  {
    kind: "SemStructFieldTypeMismatch",
    field: "x",
    expected: "i32",
    found: "str",
  },
  {
    kind: "SemArgumentTypeMismatch",
    argIndex: 1,
    calleeKind: "function",
    calleeName: "f",
    expected: "i32",
    found: "str",
  },
  {
    kind: "SemArgumentTypeMismatchConflict",
    argIndex: 1,
    calleeKind: "function",
    calleeName: "f",
    expected: "i32",
    found: "str",
  },
  {
    kind: "SemCallReturnTypeMismatch",
    calleeName: "f",
    expected: "i32",
    found: "str",
  },
  { kind: "SemNoMethodOnType", method: "foo", typeName: "P" },
  {
    kind: "SemAmbiguousMethod",
    method: "m",
    typeName: "P",
    traits: ["A", "B"],
  },
  { kind: "SemLogicalOperandsMustBeBool" },
  { kind: "SemBitwiseRequiresInteger" },
  { kind: "SemArithmeticOperandNotNumeric", side: "left", found: "str" },
  { kind: "SemShiftedValueMustBeInteger" },
  { kind: "SemShiftAmountMustBeInteger" },
  { kind: "SemNotRequiresBoolOrInteger", found: "str" },
  { kind: "SemRepeatArrayElementMustBeCopy", found: "S" },
  { kind: "SemIfConditionMustBeBool" },
  { kind: "SemComparisonNotSupported", relation: "ordering" },
  { kind: "SemComparisonOperandsSameType" },
  { kind: "SemArithmeticOperandsSameType" },
  { kind: "SemBitwiseOperandsSameType" },
  { kind: "SemArrayElementsSameType", expected: "i32", found: "str" },
  { kind: "SemMatchArmsIncompatible" },
  { kind: "SemIfBranchesIncompatible" },
  { kind: "SemLiteralOutOfRange", typeName: "u8" },
  { kind: "SemUnexpectedIntLiteralRangeCheck", typeName: "u8" },
  { kind: "SemUnexpectedFloatLiteralRangeCheck", typeName: "f64" },
  { kind: "SemArrayIndexOutOfBounds", index: "5", length: "4" },
  { kind: "SemCannotInferEmptyArrayElementType" },
  { kind: "SemCannotInferGenericParam", paramName: "T" },
  { kind: "SemCannotDereferenceNonReference" },
  { kind: "SemCannotIndexNonArray", found: "i32" },
  { kind: "SemFieldAccessOnNonStruct" },
  { kind: "SemStructHasNamedFields", structName: "S" },
  { kind: "SemUnitStructCannotUseParens", structName: "S" },
  { kind: "SemFieldProvidedForUnitStruct", field: "x", structName: "S" },
  { kind: "SemMissingRequiredField", field: "x", structName: "S" },
  { kind: "SemVariantTakesNoArguments", variant: "V", count: 2 },
  { kind: "SemVariantHasNamedFields", variant: "V" },
  { kind: "SemVariantIsTupleVariantConstruct", variant: "V" },
  { kind: "SemVariantIsUnitVariantConstruct", variant: "V" },
  {
    kind: "SemConstructorArgCountMismatch",
    calleeKind: "tuple struct",
    name: "P",
    expected: 2,
    count: 1,
  },
  {
    kind: "SemTurbofishArgCountMismatch",
    calleeName: "f",
    declared: 1,
    supplied: 2,
  },
  { kind: "SemNonExhaustivePatterns", missing: "`A`, `B`" },
  { kind: "SemUnreachablePattern" },
  { kind: "SemOrPatternInconsistentNames", names: "`x`", single: true },
  { kind: "SemOrPatternInconsistentBinding", name: "x" },
  { kind: "SemVariantNotTupleVariant", variant: "V" },
  { kind: "SemVariantNotStructVariant", variant: "V" },
  { kind: "SemPatternExpectedStruct", expected: "S", found: "T" },
  { kind: "SemStructNotTupleStruct", name: "S" },
  { kind: "SemStructNoNamedFields", name: "S" },
  { kind: "SemVariantHasFieldsPattern", variant: "V" },
  {
    kind: "SemPatternFieldCountMismatch",
    label: "struct `S`",
    fieldCount: 2,
    patternCount: 1,
  },
  { kind: "SemSlicePatternMultipleRest", restCount: 2 },
  { kind: "SemSlicePatternLengthAtLeast", length: 3, minCount: 4 },
  { kind: "SemSlicePatternLengthExactly", length: 3, exactCount: 4 },
  { kind: "SemRangeBoundsSameType", start: "i32", end: "char" },
  { kind: "SemRangeLowerGreaterThanUpper", low: "5", high: "1" },
  { kind: "SemCannotBindMutThroughSharedRef", name: "x" },
  { kind: "SemCannotBindMutPlaceNotMutable", name: "x" },
  { kind: "SemReturnsReferenceToLocal", name: "x" },
  { kind: "SemStructLiteralFieldBorrowsLocal", field: "f", name: "x" },
  { kind: "SemNotABorrowablePlace" },
  { kind: "SemCannotAssignToImmutableBinding" },
  { kind: "SemCannotAssignThroughSharedReference" },
  { kind: "OwnBorrowMutThroughShared", place: "x", through: "r" },
  { kind: "OwnBorrowMutNotDeclaredMut", baseName: "x" },
  {
    kind: "OwnConflictingBorrows",
    place: "x",
    first: "&",
    firstOffset: "1",
    second: "&mut",
    secondOffset: "2",
  },
  { kind: "OwnUseOfUninitializedBinding", name: "x" },
  { kind: "OwnUseOfMovedValue", name: "x" },
  { kind: "OwnUseOfPossiblyMovedValue", name: "x" },
  { kind: "OwnUseOfPossiblyUninitializedBinding", name: "x" },
  { kind: "OwnCannotMoveOutBorrowInstead", place: "x" },
  { kind: "OwnCannotMoveOutOfReference", place: "*r" },
  { kind: "OwnConditionalDropFlag", name: "x" },
  { kind: "OwnAmbiguousDrop", name: "x" },
];

const KNOWN_CODES = new Set<DiagnosticCode>([
  "HEDGE-LEX-001",
  "HEDGE-LEX-002",
  "HEDGE-LEX-003",
  "HEDGE-LEX-004",
  "HEDGE-LEX-005",
  "HEDGE-LEX-006",
  "HEDGE-LEX-007",
  "HEDGE-LEX-008",
  "HEDGE-LEX-009",
  "HEDGE-PARSE-001",
  "HEDGE-PARSE-002",
  "HEDGE-PARSE-003",
  "HEDGE-PARSE-004",
  "HEDGE-PARSE-005",
  "HEDGE-PARSE-006",
  "HEDGE-NAME-001",
  "HEDGE-NAME-002",
  "HEDGE-NAME-003",
  "HEDGE-NAME-004",
  "HEDGE-NAME-005",
  "HEDGE-NAME-006",
  "HEDGE-NAME-007",
  "HEDGE-TYPE-001",
  "HEDGE-TYPE-002",
  "HEDGE-TYPE-003",
  "HEDGE-TYPE-004",
  "HEDGE-TYPE-005",
  "HEDGE-TYPE-006",
  "HEDGE-TYPE-007",
  "HEDGE-TYPE-008",
  "HEDGE-TYPE-009",
  "HEDGE-TYPE-010",
  "HEDGE-TYPE-011",
  "HEDGE-TYPE-012",
  "HEDGE-TYPE-013",
  "HEDGE-PATTERN-001",
  "HEDGE-PATTERN-002",
  "HEDGE-PATTERN-003",
  "HEDGE-PATTERN-004",
  "HEDGE-PATTERN-005",
  "HEDGE-PATTERN-006",
  "HEDGE-PATTERN-007",
  "HEDGE-CONST-001",
  "HEDGE-CONST-002",
  "HEDGE-CONST-003",
  "HEDGE-CONST-004",
  "HEDGE-BORROW-CHECK-001",
  "HEDGE-BORROW-CHECK-002",
  "HEDGE-BORROW-CHECK-003",
  "HEDGE-BORROW-CHECK-005",
  "HEDGE-BORROW-CHECK-006",
  "HEDGE-LIFETIME-001",
  "HEDGE-LIFETIME-002",
  "HEDGE-MOVE-001",
  "HEDGE-MOVE-002",
  "HEDGE-MOVE-003",
  "HEDGE-MOVE-004",
  "HEDGE-LINT-001",
  "HEDGE-LINT-002",
  "HEDGE-LINT-003",
  "HEDGE-LINT-004",
  "HEDGE-TRAIT-001",
  "HEDGE-TRAIT-002",
  "HEDGE-TRAIT-003",
  "HEDGE-TRAIT-004",
  "HEDGE-TRAIT-005",
  "HEDGE-TRAIT-006",
  "HEDGE-TRAIT-007",
  "HEDGE-TRAIT-008",
  "HEDGE-ITEM-001",
  "HEDGE-UNSUPPORTED-001",
]);

describe("DiagnosticKind registry", (): void => {
  it.each(
    SAMPLE_KINDS.map((kind): [string, DiagnosticKind] => [kind.kind, kind]),
  )(
    "%s maps to a known code and renders non-empty text",
    (_name, kind): void => {
      const code = codeOf(kind);
      expect(KNOWN_CODES.has(code)).toBe(true);

      const message = renderDiagnosticMessage(kind);
      expect(message.length).toBeGreaterThan(0);
      expect(message).not.toContain("undefined");
      expect(message).not.toContain("[object Object]");
    },
  );

  it("derives the built diagnostic's code from its kind", (): void => {
    for (const kind of SAMPLE_KINDS) {
      const severity = codeOf(kind).startsWith("HEDGE-LINT")
        ? warningDiagnostic
        : errorDiagnostic;
      expect(severity(kind, none()).code).toBe(codeOf(kind));
    }
  });

  it("has a code entry and a sample for every variant, in sync", (): void => {
    const sampledTags = new Set(SAMPLE_KINDS.map((kind) => kind.kind));
    expect(sampledTags.size).toBe(SAMPLE_KINDS.length);
    expect(CODE_BY_KIND.size).toBe(sampledTags.size);
  });
});
